apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
  labels:
    app: test
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      run: test
  template:
    metadata:
      labels:
        run: test
        app: test
        version: v1
    spec:
      containers:
      - image: syjsmk/test
        name: test
        ports:
        - containerPort: 9999
